export interface StockItem {
  id: string;
  name: string;
  unit: string;
  category?: string;
}

export const DRY_STOCK_ITEMS: StockItem[] = [
  { id: "jasmine-rice", name: "Jasmine Rice (20kg) Topaz", unit: "Bag" },
  { id: "coconut-milk", name: "MP Coconut Milk", unit: "Ctn" },
  { id: "veg-oil", name: "Veg Oil 20L", unit: "Jerry Can" },
  { id: "dark-soy", name: "Superior Dark Soy (600ml)", unit: "Btl" },
  { id: "sweet-soy", name: "Sweet Soy Sauce(ABC)", unit: "Btl" },
  { id: "oyster-sauce", name: "PC Oyster (Caterer)", unit: "Ctn" },
  { id: "mchef-oyster", name: "MChef OysterGF(4.5L)", unit: "Gallon" },
  { id: "mchef-mush", name: "MChef Mush'GF (V)", unit: "Ctn" },
  { id: "chicken-powder", name: "Chicken Powder", unit: "Bag" },
  { id: "salted-black-bean", name: "Salted Black Bean", unit: "Pack" },
  { id: "mchef-soy", name: "MChef Soy Sauce GF", unit: "Gallon" },
  { id: "plum-sauce", name: "Plum Sauce", unit: "Btl" },
  { id: "baking-powder", name: "Baking Powder", unit: "Tin" },
  { id: "g-mountain", name: "G' Mountain (Green Cap)", unit: "Btl" },
  { id: "fish-sauce", name: "Fish Sauce", unit: "Ctn" },
  { id: "cook-tamad", name: "Cook' Tama'd(พันท้าย 454g)", unit: "Ctn" },
  { id: "tomato-sauce", name: "Tomato Sauce", unit: "Gallon" },
  { id: "sweet-chilli", name: "Sweet Chilli Sauce 4.5L", unit: "Gallon" },
  { id: "pantai-paste", name: "Pantai น้ำพริกเผา", unit: "Big Can" },
  { id: "cock-massaman", name: "Cock' Massaman", unit: "Tub" },
  { id: "maesri-red", name: "Maesri Red", unit: "Ctn (12 Can)" },
  { id: "maesri-green", name: "Maesri Green", unit: "Ctn (12 Can)" },
  { id: "maesri-karee", name: "Maesri Karee", unit: "Ctn (12 Can)" },
  { id: "maesri-panang", name: "Maesri Panang", unit: "Ctn (12 Can)" },
  { id: "prik-khing", name: "Prik khing paste", unit: "Ctn (12 Can)" },
  { id: "chu-chee", name: "Chu Chee Curry Paste", unit: "Ctn (12 Can)" },
  { id: "turmeric-powder", name: "Turmuric Powder", unit: "Bag" },
  { id: "cock-tom-yum", name: "Cock' Tom Yum Paste", unit: "Btl" },
  { id: "chilli-garlic", name: "Chilli & Garlic sauce (Ayam)", unit: "Ctn" },
  { id: "ginger-strips", name: "Ginger Strips", unit: "Jar" },
  { id: "krachai-strips", name: "Krachai Strips", unit: "Jar" },
  { id: "green-pepper", name: "Green Pepper Corn", unit: "Jar" },
  { id: "galangal-sliced", name: "Galangal Sliced", unit: "Jar" },
  { id: "dried-fungus", name: "Dried Black Fungus (1kg)", unit: "Bag" },
  { id: "pig-kong-stick", name: "Pig'n Kongm'n R/Stick", unit: "Pack" },
  { id: "frozen-chilli", name: "Frozen Chilli (No Stem)", unit: "Pack" },
  { id: "dried-chilli", name: "Dried Chilli", unit: "Kg" },
  { id: "sen-yai", name: "เส้นใหญ่(ตัดแล้ว)", unit: "Pack" },
  { id: "sen-pad-thai", name: "เส้นผัดไทย (Pigeon)", unit: "Ctn" },
  { id: "glass-noodles", name: "Glass Noodles (วุ้นเส้น ห่อเล็ก)", unit: "Pack" },
  { id: "hokkian-noodles", name: "Hokkian Noodles", unit: "Pack" },
  { id: "prawn-toast", name: "Prawn Toast", unit: "Pack" },
  { id: "prawn-cracker", name: "Prawn Cracker", unit: "Box" },
  { id: "fish-cake", name: "Fish cake", unit: "Pack" },
  { id: "roti-plain", name: "Roti Plain Malabar", unit: "Pack" },
  { id: "tofu-900g", name: "Original Tofu 900g", unit: "Pack" },
  { id: "sugar-white", name: "Sugar White (25Kg)", unit: "Bag" },
  { id: "self-raising-flour", name: "Self Raising Flour", unit: "Bag" },
  { id: "tapioca-starch", name: "Tadpioca Starch", unit: "Bag" },
  { id: "bi-carbonate", name: "Bi-Carbonate", unit: "kg" },
  { id: "lychees", name: "Lychees", unit: "Ctn" },
  { id: "pineapple-pieces", name: "Pineapple Pieces", unit: "Ctn" },
  { id: "bamboo-shoots", name: "Sliced Bamboo Shoots", unit: "Ctn" },
  { id: "cashew-nuts", name: "Cashew Nuts (Big Bag)", unit: "Bag" },
  { id: "floor-cleaner", name: "Big Red Floor Cleaner", unit: "Cube" },
  { id: "chocolate-topping", name: "Chocolate Topping (3L Cottees)", unit: "Btl" },
  { id: "caramel-topping", name: "Caramel Topping (3L Cottees)", unit: "Btl" },
  { id: "strawberry-topping", name: "Strawberry Topping (3L Cottees)", unit: "Btl" },
  { id: "fried-shallot", name: "Fried Shallot", unit: "Bag" },
  { id: "fried-garlic", name: "Fried Garlic", unit: "Bag" },
  { id: "spring-roll-pastry", name: "TYJ Spring Rolls Pastry", unit: "Ctn" },
  { id: "vinegar", name: "Vinegar", unit: "Gallon" },
  { id: "salt", name: "Salt", unit: "Kg" },
  { id: "water-chestnut", name: "Water Chestnut", unit: "Big Can" },
  { id: "breadcrumbs", name: "Fine Breadcrumbs", unit: "kg" },
  { id: "cling-wrap", name: "Cling Wrap (33cm)", unit: "Unit" },
  { id: "white-pepper", name: "White Pepper", unit: "Bag" },
  { id: "wok-brush", name: "Wok Brush Standard", unit: "Unit" },
  { id: "kiwi-knife-171", name: "Kiwi Knife 171", unit: "Unit" },
  { id: "kiwi-knife-10cm", name: "Kiwi Knife (10cm)", unit: "Unit" },
  { id: "cherries", name: "Maraschino Cherries Red Stem", unit: "Btl" },
  { id: "condensed-milk", name: "Nestle Condensed Milk", unit: "Ctn" },
  { id: "peanuts", name: "Crunched Rst'ed Peanuts", unit: "Kg" },
  { id: "black-sticky-rice", name: "Black Sticky Rice (2kg)", unit: "Bag" },
  { id: "sticky-rice", name: "Sticky Rice (10kg)", unit: "Bag" },
  { id: "mayonnaise", name: "Mayonnaise (1kg)", unit: "Btl" },
  { id: "container-4-8l", name: "4.8L Square Container with Lid", unit: "Unit" },
  { id: "container-3-1l", name: "3.1L Square Container with Lid", unit: "Unit" },
  { id: "sponge", name: "Scotch-Brite Sponge (Large)", unit: "Pc" },
  { id: "wok-16", name: "Wok 16\" Deep", unit: "Unit" },
  { id: "ladle-11-4", name: "Ladle w/wooden handle (11.4 cm)", unit: "Unit" },
  { id: "ladle-12-8", name: "Ladle w/wooden handle (12.8 cm)", unit: "Unit" },
  { id: "turner", name: "Turner (ตะหลิวด้มยาว)", unit: "Unit" },
  { id: "dishwasher-machine", name: "Dishwasher [For Machine] (20L)", unit: "Cube" },
  { id: "dishwasher-hand", name: "Dishwasher [By Hand] (20L)", unit: "Cube" },
  { id: "palm-sugar", name: "Palm Sugar", unit: "Ctn" },
  { id: "oven-cleaner", name: "Oven Cleaner", unit: "Gallon" },
  { id: "hales-red", name: "Hales's (Red)", unit: "Btl" },
  { id: "honey", name: "Honey (3L Blossom Pure)", unit: "Btl" },
  { id: "gloves-m", name: "Powdered Gloved (M)", unit: "Ctn" },
];

export const PACKAGING_ITEMS: StockItem[] = [
  { id: "bcb-kraft-small", name: "BCB TM Kraft Small", unit: "Ctn" },
  { id: "bcb-kraft-medium", name: "BCB TM Kraft Medium", unit: "Ctn" },
  { id: "paper-towel", name: "Paper Towel 24x24 cm", unit: "Ctn" },
  { id: "sauce-30cc", name: "30cc Hinged Lid Sauce Container", unit: "Ctn" },
  { id: "sauce-25cc", name: "25cc Hinged Lid Sauce Container", unit: "Ctn" },
  { id: "tray-clam", name: "Plastic Tray Clam (3H)", unit: "Ctn" },
  { id: "lid-rect", name: "Lid Rectangular", unit: "Ctn" },
  { id: "rect-500", name: "500 Rectangular", unit: "Ctn" },
  { id: "rect-750", name: "750 Rectangular", unit: "Ctn" },
  { id: "rect-1000", name: "1000 Rectangular", unit: "Ctn" },
  { id: "plastic-bag-m", name: "Plastic Bag (M)", unit: "Pack" },
  { id: "napkin-white", name: "Quilted Dinner Napkin GT Fold White", unit: "Ctn" },
  { id: "sandwich-wedge", name: "(M) BioBoard Sandwich Wedge", unit: "Pack" },
  { id: "snackbox", name: "(M) BioBoard Regular Snackbox", unit: "Pack" },
  { id: "bin-liner-82l", name: "82L Heavy Duty Bin Liner", unit: "Ctn" },
];

export const FRESH_PRODUCE_ITEMS: StockItem[] = [
  { id: "basil", name: "Basil", unit: "Pack" },
  { id: "beansprout", name: "Beansprout", unit: "Bag" },
  { id: "broccoli", name: "Broccoli", unit: "Ctn" },
  { id: "brown-onion", name: "Brown Onion", unit: "Bag" },
  { id: "buk-choy", name: "Buk Choy", unit: "Bunch" },
  { id: "cabbage-white", name: "Cabbage (White)", unit: "Head" },
  { id: "capsicum-mixed", name: "Capsicum (Mixed)", unit: "Ctn" },
  { id: "carrot", name: "Carrot", unit: "Ctn" },
  { id: "cherry-tomato", name: "Cherry Tomato", unit: "Punnet" },
  { id: "chilli-red", name: "Chilli (Red Cayenne)", unit: "kg" },
  { id: "chives", name: "Chives", unit: "Bunch" },
  { id: "coriander", name: "Coriander", unit: "Bunch" },
  { id: "cos-lettuce", name: "Cos Lettuce", unit: "Bag" },
  { id: "cucumber", name: "Cucumber", unit: "Bag" },
  { id: "eggplant", name: "Eggplant", unit: "Head" },
  { id: "garlic-peeled", name: "Garlic (Peeled)", unit: "Pack" },
  { id: "green-bean", name: "Green Bean", unit: "Ctn" },
  { id: "ginger-pc", name: "Ginger", unit: "Pc" },
  { id: "kailan", name: "Kailan", unit: "Bunch" },
  { id: "lemon", name: "Lemon", unit: "Ctn" },
  { id: "lemongrass", name: "Lemongrass", unit: "Bunch" },
  { id: "lime-cocktails", name: "Lime (for Cocktails)", unit: "Ctn" },
  { id: "mint", name: "Mint", unit: "Bunch" },
  { id: "mixed-salad", name: "Mixed Salad", unit: "Box" },
  { id: "mushroom-button", name: "Mushroom (Button)", unit: "Box" },
  { id: "papaya", name: "Papaya", unit: "Head" },
  { id: "pineapple", name: "Pineapple", unit: "Head" },
  { id: "potatoes-purple", name: "Potatoes (Washed Purple)", unit: "Bag" },
  { id: "pumpkin", name: "Pumpkin", unit: "Head" },
  { id: "red-onion", name: "Red Onion", unit: "kg" },
  { id: "shallot", name: "Shallot", unit: "Bag" },
  { id: "egg-700g", name: "Egg (700g)", unit: "Ctn" },
];
